added briefRepresentation in query params to show or not the role attributes
silentpartnersoftware/Keycloak.Net pull request #52
Opened 2024-10-02 00:07 UTC by endrit-gjocaj

2024-10-02 15:16 UTC, sps-campbellwray requested changes
@endrit-gjocaj I believe this should be changed to `bool?` and the default value should be set to `null`. This way it will use the Keycloak defaults, as opposed to this library imposing it's own default values.

If for some reason this doesn't work, please let me know 😄

2024-10-02 15:44 UTC, endrit-gjocaj commented
> @endrit-gjocaj I believe this should be changed to `bool?` and the default value should be set to `null`. This way it will use the Keycloak defaults, as opposed to this library imposing it's own default values.
> 
> If for some reason this doesn't work, please let me know 😄

@sps-campbellwray yes your point is valid, I wanted to change the default one to false, in order to always get the attributes since the default one (true) ignores them. What do you think?

2024-10-02 15:57 UTC, sps-campbellwray commented
@endrit-gjocaj I suspect that the intention of the Keycloak team is to ensure that the requests run quickly and don't return unnecessary information, which is why the default is to ignore the attributes. 

By setting it to null, that will also mean that users who are already using Keycloak.Net will continue to have a consistent experience, but that the option will be available to those users who need it.

2024-10-03 07:39 UTC, endrit-gjocaj commented
@sps-campbellwray okay thank you, check it now

2024-10-03 19:52 UTC, sps-campbellwray approved these changes

2024-10-03 19:52 UTC, merged

2024-10-04 18:58 UTC, sps-campbellwray commented
@endrit-gjocaj I have just deployed it under 1.0.30.

Thanks for your contribution!